[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn wazan.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/admin/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
