# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.CharField(choices=[('starter', 'باقة البداية'), ('professional', 'الباقة الاحترافية'), ('company', 'باقة الشركات'), ('enterprise', 'باقة المؤسسات')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_farms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(blank=True, null=True)),
                ('max_fields', models.PositiveIntegerField(blank=True, null=True)),
                ('max_greenhouses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_cycles', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ai_reports', models.PositiveIntegerField(blank=True, null=True)),
                ('has_sensors', models.BooleanField(default=False)),
                ('has_cameras', models.BooleanField(default=False)),
                ('has_pumps', models.BooleanField(default=False)),
                ('has_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('trial', 'تجريبي'), ('expired', 'منتهي'), ('suspended', 'موقوف')], default='trial', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ai_addon', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('paid', 'مدفوعة'), ('pending', 'معلقة'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('card', 'بطاقة ائتمان'), ('bank_transfer', 'تحويل بنكي'), ('mada', 'مدى')], max_length=20)),
                ('ref_number', models.CharField(blank=True, max_length=100)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issued_at'],
            },
        ),
    ]
