# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(choices=[('irrigation', 'ري'), ('fertilization', 'تسميد'), ('harvest', 'حصاد'), ('pest_control', 'مكافحة آفات'), ('planting', 'زراعة'), ('pruning', 'تقليم'), ('soil_prep', 'تحضير التربة'), ('other', 'أخرى')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('in_progress', 'جاري'), ('done', 'منتهي'), ('cancelled', 'ملغي')], default='planned', max_length=20)),
                ('date', models.DateField()),
                ('duration_hrs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='cycles.agriculturalcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.field')),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.greenhouse')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية زراعية',
                'verbose_name_plural': 'العمليات الزراعية',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='operations/attachments/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations.operation')),
            ],
        ),
    ]
