# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('irrigation', 'ري'), ('fertilization', 'تسميد'), ('harvest', 'حصاد'), ('maintenance', 'صيانة'), ('inspection', 'فحص'), ('other', 'أخرى')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'حرج'), ('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('in_progress', 'جاري'), ('done', 'منجز'), ('cancelled', 'ملغي'), ('overdue', 'متأخر')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.farm')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
