# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labor', 'عمالة'), ('seeds', 'بذور وشتلات'), ('fertilizer', 'أسمدة'), ('pesticide', 'مبيدات'), ('water', 'مياه'), ('electricity', 'كهرباء'), ('fuel', 'وقود'), ('equipment', 'معدات'), ('maintenance', 'صيانة'), ('transport', 'نقل'), ('packaging', 'تعبئة وتغليف'), ('other', 'أخرى')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finances/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cycles.agriculturalcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farms.farm')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_type', models.CharField(choices=[('market', 'سوق'), ('wholesaler', 'جملة'), ('retailer', 'تجزئة'), ('direct', 'مباشر'), ('export', 'تصدير'), ('other', 'أخرى')], default='market', max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cycles.agriculturalcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farms.farm')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'المبيعات',
                'ordering': ['-date'],
            },
        ),
    ]
