# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly_summary', 'ملخص أسبوعي'), ('cycle_analysis', 'تحليل دورة زراعية'), ('cost_analysis', 'تحليل التكاليف'), ('pest_advice', 'نصيحة لمكافحة الآفات'), ('harvest_forecast', 'توقع الحصاد'), ('irrigation_plan', 'خطة ري'), ('general', 'عام')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20)),
                ('prompt_used', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports', to='cycles.agriculturalcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='farms.farm')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reports_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقرير ذكاء اصطناعي',
                'verbose_name_plural': 'تقارير الذكاء الاصطناعي',
                'ordering': ['-created_at'],
            },
        ),
    ]
