# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('vegetables', 'خضروات'), ('fruits', 'فواكه'), ('grains', 'حبوب'), ('herbs', 'أعشاب'), ('flowers', 'زهور'), ('other', 'أخرى')], default='other', max_length=20)),
                ('avg_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='متوسط أيام النمو')),
                ('notes', models.TextField(blank=True)),
                ('icon', models.CharField(default='🌱', max_length=10)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'المحاصيل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgriculturalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('active', 'نشط'), ('harvesting', 'في مرحلة الحصاد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='planned', max_length=20)),
                ('start_date', models.DateField()),
                ('expected_end', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('target_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإنتاج المستهدف (كجم)')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإنتاج الفعلي (كجم)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_created', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='farms.field')),
                ('greenhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='farms.greenhouse')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cycles.crop')),
            ],
            options={
                'verbose_name': 'دورة زراعية',
                'verbose_name_plural': 'الدورات الزراعية',
                'ordering': ['-start_date'],
            },
        ),
    ]
