# Generated by Django 6.0.5 on 2026-05-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المزرعة')),
                ('location', models.CharField(blank=True, max_length=300)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة (هكتار)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'مزرعة',
                'verbose_name_plural': 'المزارع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('sandy', 'رملية'), ('loamy', 'طينية رملية'), ('clay', 'طينية'), ('silty', 'طمية'), ('rocky', 'صخرية')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'verbose_name': 'حقل',
                'verbose_name_plural': 'الحقول',
            },
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gh_type', models.CharField(choices=[('standard', 'عادي'), ('cooled', 'مكيف'), ('shaded', 'مظلل'), ('tunnel', 'نفق')], default='standard', max_length=20)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعة (شتلة)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to='farms.farm')),
            ],
            options={
                'verbose_name': 'بيت محمي',
                'verbose_name_plural': 'البيوت المحمية',
            },
        ),
    ]
